
-- Code to add SSAS MD system user

USE [master]
GO
CREATE LOGIN [NT SERVICE\MSOLAP$DOWSQL2019] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
USE [WideWorldImportersDW]
GO
CREATE USER [SSASMDSys] FOR LOGIN [NT SERVICE\MSOLAP$DOWSQL2019]
GO
USE [WideWorldImportersDW]
GO
ALTER ROLE [db_datareader] ADD MEMBER [SSASMDSys]
GO
